/* Help indices for PEW_HELP file */

#define PEW_HELPFILE	"PEW_HELP"

enum helpindex
{
     /*  0 */ HLP_FILEMENU, HLP_EDITCMD, HLP_OPTMENU, HLP_EXECCMD, HLP_ANLYZMENU,
     /*  5 */ HLP_COMPILE, HLP_MAINMENU, HLP_LOADFILE, HLP_SAVEFILE, HLP_RENAME,
     /* 10 */ HLP_NEWFILE, HLP_GOTOLINE, HLP_OSSHELL, HLP_QUIT, HLP_TABSIZE,
     /* 15 */ HLP_BACKUP, HLP_FILLCHAR, HLP_WRAPMODE, HLP_LEFTSRCH, HLP_RIGHTSRCH,
     /* 20 */ HLP_SRCHTEXT, HLP_TRANSTXT, HLP_CASESENS, HLP_CFGAUTO, HLP_CFGSAVE,
     /* 25 */ HLP_FIXDCMDS, HLP_MOVECMDS, HLP_BLKCMDS, HLP_SRCHTRANS, HLP_MISC,
     /* 30 */ HLP_CURSUP, HLP_CURSDOWN, HLP_CURSLEFT, HLP_CURSRGHT, HLP_HOME,
     /* 35 */ HLP_END, HLP_PGUP, HLP_PGDN, HLP_DELETE, HLP_HELP,
     /* 40 */ HLP_WORDLEFT, HLP_WORDRGHT, HLP_TOF, HLP_EOF, HLP_MARKPLACE,
     /* 45 */ HLP_GOTOMARK, HLP_SETBMARK, HLP_SETCMARK, HLP_COPYTEXT, HLP_BPASTE,
     /* 50 */ HLP_CPASTE, HLP_FSEARCH, HLP_BSEARCH, HLP_TRANSLATE, HLP_LMATCH,
     /* 55 */ HLP_RMATCH, HLP_UNDO, HLP_RECMACRO, HLP_OVRMACRO, HLP_SETMACRO,
     /* 60 */ HLP_IDENTONLY, HLP_FILECH, HLP_TRANS, HLP_READSCRAP, HLP_WRITESCRAP,
     /* 65 */ HLP_LANGHELP, HLP_TEMPLATE, HLP_DELLINE, HLP_BACKSPACE, HLP_EXEC_ENVIRONMENT,
     /* 70 */ HLP_ANIMATE, HLP_SETLNBRKPT, HLP_PASSCNT, HLP_BRKPROCESS, HLP_BRKACTION,
     /* 75 */ HLP_BRKOTHER, HLP_DUMPPANE, HLP_DUMPPROCESS, HLP_TRANSBRKTYPES, HLP_SETTRANSBRKPT,
     /* 80 */ HLP_VIEWTRANSSTATS, HLP_SETIPBRKPT, HLP_VIEWIPSTATS, HLP_VIEWCEP, HLP_TIMELIMIT,
     /* 85 */ HLP_BRKSUSPEND, HLP_VIEWBRKPTS, HLP_BRKPTDEL, HLP_CONFIRMDEL, HLP_LOADLOG,
     /* 90 */ HLP_BRKPTREADY, HLP_BRKCONTROL, HLP_BRKRESET, HLP_BRKACTIVATE, HLP_TRANSSTATS,
     /* 95 */ HLP_IPSTATS, HLP_BRKPTBROWSE, HLP_DELINTR, HLP_QUITEXEC, HLP_RANDOMSEED,
     /*100 */ HLP_ALZINDEP, HLP_ALZFROM, HLP_ALZTO, HLP_ALZSTEP, HLP_ALZEDDEP,
     /*105 */ HLP_ALZGO, HLP_CRIT_QUIT, HLP_ALZTIME,

    HLP_NUMHELPS
};
